import Link from "next/link";
import { ArrowUpRight, FileText, ShieldCheck, CircleAlert } from "lucide-react";
import Navbar from "@/components/Navbar";

export default function Home() {
  return <div className="min-h-screen bg-[#f7f6f2]"><Navbar /><main className="mx-auto max-w-6xl px-5 py-12 sm:px-8 sm:py-20"><section className="max-w-3xl"><p className="eyebrow">Procurement review</p><h1 className="mt-4 text-4xl font-medium tracking-[-.045em] text-[#162333] sm:text-6xl">Review the bid.<br />We’ll bring the evidence.</h1><p className="mt-6 max-w-xl text-base leading-7 text-[#5d6872] sm:text-lg">Provide the tender and bidder documents. We identify what needs to be checked, reconcile the available evidence, and surface only the items that need an officer’s attention.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/tender" className="focus-ring inline-flex items-center gap-3 bg-[#163a5f] px-5 py-3 text-sm font-medium text-white transition-colors hover:bg-[#204b76]">Start a bid review <ArrowUpRight className="h-4 w-4" /></Link><Link href="/history" className="focus-ring inline-flex items-center gap-3 border border-[#cfd5d5] bg-[#fffefa] px-5 py-3 text-sm font-medium text-[#263746] transition-colors hover:bg-white">View review history</Link></div></section><section className="mt-20 border-y border-[#d9ddd9] py-7 sm:grid sm:grid-cols-3 sm:gap-8"><Feature icon={<FileText className="mt-0.5 h-5 w-5 shrink-0 text-[#2e638d]" />} title="Requirements, not files" text="Documents become evidence attached to the relevant procurement requirement." /><Feature icon={<CircleAlert className="mt-0.5 h-5 w-5 shrink-0 text-[#a85e31]" />} title="Exceptions come first" text="Straightforward evidence stays quiet; contradictions are brought forward." extra /><Feature icon={<ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-[#2e638d]" />} title="The officer decides" text="Every finding is a review aid, with its source material available when needed." extra /></section></main></div>;
}

function Feature({ icon, title, text, extra = false }: { icon: React.ReactNode; title: string; text: string; extra?: boolean }) { return <div className={`flex gap-4 py-4 sm:py-0 ${extra ? "border-t border-[#e0e2de] sm:border-t-0" : ""}`}>{icon}<div><p className="text-sm font-medium">{title}</p><p className="mt-1 text-sm leading-6 text-[#68737c]">{text}</p></div></div>; }
