"""Action Studio Domain Models.

Defines persistent Pydantic domain models, enumerations, DTOs, evidence references,
and audit structures for the Backend Action Studio vertical slice.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ActionDocumentType(str, Enum):
    """Supported Action Studio document types."""
    NOTE_FOR_FILE = "NOTE_FOR_FILE"
    EVALUATION_COMMITTEE_REPORT = "EVALUATION_COMMITTEE_REPORT"
    LETTER_OF_AWARD = "LETTER_OF_AWARD"
    REJECTION_LETTER = "REJECTION_LETTER"
    REGRET_LETTER = "REGRET_LETTER"


class ActionDocumentStatus(str, Enum):
    """Lifecycle statuses for Action Studio document drafts.

    Note: DISPATCHED is explicitly omitted as per Action Studio scope boundaries.
    """
    DRAFT = "DRAFT"
    EDITED = "EDITED"
    READY_FOR_APPROVAL = "READY_FOR_APPROVAL"
    APPROVED = "APPROVED"


class EvidenceReference(BaseModel):
    """Structured evidence provenance reference linking a factual claim to canonical evidence."""
    requirement_id: Optional[str] = Field(None, description="Tender requirement ID.")
    finding_id: Optional[str] = Field(None, description="Compliance finding ID.")
    evaluation_id: Optional[str] = Field(None, description="Evaluation run ID.")
    document_id: Optional[str] = Field(None, description="Source document UUID.")
    document_name: Optional[str] = Field(None, description="Source document filename.")
    page_number: Optional[int] = Field(None, description="Exact page number in source document, if available.")
    quote: Optional[str] = Field(None, description="Verbatim source text quote.")
    provenance_summary: Optional[str] = Field(None, description="Summary of evidence context.")


class ActionStudioDocument(BaseModel):
    """Canonical representation of an officer-controlled Action Studio document draft."""
    id: str = Field(..., description="Unique document UUID.")
    procurement_id: str = Field(..., description="Target procurement workspace UUID.")
    document_type: ActionDocumentType = Field(..., description="Type of Action Studio document.")
    title: str = Field(..., description="Human-readable title of the document.")
    status: ActionDocumentStatus = Field(default=ActionDocumentStatus.DRAFT, description="Current lifecycle status.")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Creation timestamp.")
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Last modification timestamp.")
    created_by: str = Field(default="HUMAN_PROCUREMENT_OFFICER", description="Actor who initiated draft creation.")
    decision_authority: str = Field(default="HUMAN_PROCUREMENT_OFFICER", description="Decision authority boundary.")
    source_evaluation_references: Dict[str, Any] = Field(default_factory=dict, description="References to canonical technical & financial evaluation runs.")
    content: str = Field(..., description="Document body content in formatted text / markdown.")
    evidence_references: List[EvidenceReference] = Field(default_factory=list, description="Traceable evidence references.")
    is_ai_generated: bool = Field(default=True, description="Whether the initial content was generated by AI.")
    is_draft: bool = Field(default=True, description="Explicit draft indicator.")
    version: int = Field(default=1, description="Sequential document version number.")
    target_bidder_id: Optional[str] = Field(None, description="Target bidder UUID for bidder-specific letters.")
    target_bidder_name: Optional[str] = Field(None, description="Target bidder legal name for bidder-specific letters.")
    approved_by: Optional[str] = Field(None, description="Approving officer actor identity.")
    approved_at: Optional[datetime] = Field(None, description="Timestamp when draft was formally approved.")

    class Config:
        from_attributes = True


class ActionStudioDocumentVersion(BaseModel):
    """Immutable snapshot version history entry for an Action Studio document."""
    id: str = Field(..., description="Version snapshot UUID.")
    document_id: str = Field(..., description="Parent document UUID.")
    version: int = Field(..., description="Version number of this snapshot.")
    content: str = Field(..., description="Document content at this version.")
    status: ActionDocumentStatus = Field(..., description="Status at this version.")
    updated_by: str = Field(..., description="Actor who created this version.")
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Version timestamp.")
    change_summary: Optional[str] = Field(None, description="Description of edits made in this version.")


class ActionStudioAuditEvent(BaseModel):
    """Structured audit trail record for Action Studio actions."""
    id: str = Field(..., description="Audit event UUID.")
    event_type: str = Field(..., description="Event type (e.g. ACTION_DRAFT_CREATED, ACTION_DRAFT_APPROVED).")
    procurement_id: str = Field(..., description="Associated procurement UUID.")
    document_id: str = Field(..., description="Associated document UUID.")
    document_type: ActionDocumentType = Field(..., description="Document type.")
    actor: str = Field(..., description="Actor performing the action.")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Timestamp.")
    source_evaluation_references: Dict[str, Any] = Field(default_factory=dict, description="Canonical evaluation references.")
    version: int = Field(default=1, description="Document version at time of event.")
    details: Dict[str, Any] = Field(default_factory=dict, description="Contextual event details.")


# DTO Requests & Responses
class CreateDraftRequest(BaseModel):
    """Payload for creating a new Action Studio document draft."""
    document_type: ActionDocumentType = Field(..., description="Type of document to create.")
    target_bidder_id: Optional[str] = Field(None, description="Target bidder ID for award/rejection/regret letters.")
    title: Optional[str] = Field(None, description="Optional custom title.")
    created_by: Optional[str] = Field(default="HUMAN_PROCUREMENT_OFFICER", description="Officer identity initiating creation.")


class UpdateDraftRequest(BaseModel):
    """Payload for updating/editing an existing draft content."""
    content: str = Field(..., min_length=1, description="New document content.")
    updated_by: Optional[str] = Field(default="HUMAN_PROCUREMENT_OFFICER", description="Officer editing the draft.")
    change_summary: Optional[str] = Field(None, description="Summary of modifications.")
    mark_ready_for_approval: Optional[bool] = Field(default=False, description="Optionally update status to READY_FOR_APPROVAL.")


class ApproveDraftRequest(BaseModel):
    """Payload for approving a draft document."""
    officer_actor: str = Field(..., min_length=1, description="Identity of the approving human procurement officer.")
    notes: Optional[str] = Field(None, description="Approval notes or executive remarks.")


class ActionStudioDocumentSummary(BaseModel):
    """Summary item for Action Studio document lists."""
    id: str
    procurement_id: str
    document_type: ActionDocumentType
    title: str
    status: ActionDocumentStatus
    version: int
    created_by: str
    target_bidder_id: Optional[str] = None
    target_bidder_name: Optional[str] = None
    created_at: datetime
    updated_at: datetime
    is_draft: bool
    approved_by: Optional[str] = None
    approved_at: Optional[datetime] = None


class ActionStudioListResponse(BaseModel):
    """Response payload listing Action Studio documents for a procurement."""
    procurement_id: str
    total: int
    documents: List[ActionStudioDocumentSummary]
